### ISSUE TITLE
the role fails when ruby version is 2.3.x

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-fluentd#30]
```
2017-05-09 08:17:46 +0000 [info]: listening fluent socket on 127.0.0.1:24224
2017-05-09 08:17:46 +0000 [debug]: starting client
2017-05-09 08:17:46 +0000 [debug]: create tcp socket to node host="192.168.212.22" address="192.168.212.22" port=24284
2017-05-09 08:17:46 +0000 [debug]: trying to connect ssl session host="192.168.212.22" address="192.168.212.22" port=24284
2017-05-09 08:17:46 +0000 [debug]: ssl session connected host="192.168.212.22" port=24284
2017-05-09 08:17:46 +0000 [debug]: checking peer's certificate subject=#<OpenSSL::X509::Name:0x00000807824038>
2017-05-09 08:17:46 +0000 [debug]: ssl session connected host="192.168.212.22" port=24284
2017-05-09 08:17:46 +0000 [warn]: failed to reform records error_class=NoMethodError error="undefined method `method_defined?' for nil:NilClass"
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/2.3/ostruct.rb:171:in `new_ostruct_member'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/2.3/ostruct.rb:195:in `method_missing'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/plugin/filter_record_transformer.rb:228:in `prepare_placeholders'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/plugin/filter_record_transformer.rb:116:in `reform'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/plugin/filter_record_transformer.rb:89:in `block in filter_stream'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/event.rb:54:in `each'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/plugin/filter_record_transformer.rb:87:in `filter_stream'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/event_router.rb:150:in `block in emit'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/event_router.rb:149:in `each'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/event_router.rb:149:in `emit'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/event_router.rb:88:in `emit_stream'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/event_router.rb:79:in `emit'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/engine.rb:151:in `block in log_event_loop'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/engine.rb:149:in `each'
  2017-05-09 08:17:46 +0000 [warn]: /usr/local/lib/ruby/gems/2.3/gems/fluentd-0.12.14/lib/fluent/engine.rb:149:in `log_event_loop'
2017-05-09 08:17:46 +0000 [debug]: map:{"host"=>"${Socket.gethostname}", "@version"=>"1"} record:{"host"=>"192.168.212.22", "address"=>"192.168.212.22", "port"=>24284, "message"=>"create tcp socket to node host=\"192.168.212.22\" address=\"192.168.212.22\" port=24284"} placeholders:{"tag"=>"fluent.debug", "tag_parts"=>["fluent", "debug"], "tag_prefix"=>["fluent", "fluent.debug"], "tag_suffix"=>["fluent.debug", "debug"], "hostname"=>"rproxy1.virtualbox.reallyenglish.com"}
```

**Comment by trombik** [comment]
the latest 0.12.x does not have this issue because the plug-in, `filter_record_transformer`, has been modified a year ago.

the package is old and our own should be rolled up but the build host is broken at the moment.
